name: Create Vizualizing Codebase Diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Update diagram
        uses: kristofzerbe/hexo-generator-anything@main
        with:
          excluded_paths: "ignore,.github"